# Generated by Django 4.2.7 on 2023-11-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image_alter_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Description',
            new_name='description',
        ),
    ]
